-- 1. Top 3 employees per department by revenue
-- Business Insight: Identifies top performers in each team
with EmployeesRevenue as (
		select employees.emp_id as emp_id, employees.name as name, employees.dept_id as dept_id, 
        sum(orders.order_amount) as revenue
		from employees
		inner join orders on employees.emp_id = orders.emp_id
		group by employees.emp_id, employees.name, employees.dept_id),
	-- for ranking of employees in a department
	EmployeesRanking as (
		select *, row_number() over(partition by dept_id order by revenue desc) as ranking
		from EmployeesRevenue)
select * 
from EmployeesRanking
where ranking < 4;




-- 2.  Revenue per department per month
-- Business Insight: Revenue Generated by department per month(contribution to the company)

-- this is by using aggregate function and group by clause
select employees.dept_id, date_format(orders.order_date, '%Y-%m') as YearMonth,
sum(orders.order_amount) as RevenuePerDepartment
from employees
inner join orders on employees.emp_id = orders.emp_id
-- where date_format(orders.order_date, '%Y-%m') is Not null
group by employees.dept_id, date_format(orders.order_date, '%Y-%m')
order by employees.dept_id, date_format(orders.order_date, '%Y-%m') asc;


-- this is by using window function which is using distinct
select distinct employees.dept_id, month(orders.order_date) as Month,
sum(orders.order_amount) over(partition by employees.dept_id, month(orders.order_date)
								order by employees.dept_id asc) as revenue_per_month
from employees
inner join orders on employees.emp_id = orders.emp_id;


 


-- 3. Running total revenue per employees
-- Business Insight: Shows the Revenue Generated by an employee time by time
with RunningTotal as (
		select emp_id, order_amount, order_date, sum(order_amount) over (partition by emp_id
															 order by order_date, order_amount asc) as Running_total_Revenue
        from orders)
select * from
RunningTotal;





-- 4. Reveneue Contribution % of each employee in department
-- Business Insight: Identifies Employees' contribution towards company

-- This is done using Aggregate function and group by clause no need of distinct
with EmpInfo as (
		select employees.emp_id as emp_id, employees.name as name, employees.dept_id as dept_id, 
		sum(orders.order_amount) as emp_revenue -- Aggregate function for calculating revenue of employee
		from employees
		left join orders on employees.emp_id = orders.emp_id
		group by employees.emp_id, employees.name
),
DeptInfo as (
		select employees.dept_id as dept_id, sum(orders.order_amount) as dept_revenue -- Aggregate Function for calculating revenue of department
		from employees
		left join orders on employees.emp_id = orders.emp_id
		group by employees.dept_id
)
select EmpInfo.emp_id, EmpInfo.name, EmpInfo.dept_id, EmpInfo.emp_revenue, DeptInfo.dept_revenue,
		EmpInfo.emp_revenue * 100/nullif(DeptInfo.dept_revenue, 0) as RevenueContribution -- Formula for contribution
from EmpInfo
inner join DeptInfo on EmpInfo.dept_id = DeptInfo.dept_id
where dept_revenue is not null;


-- this is a combination of distinct,  aggregate function, window function
with EmpInfo as (
		select employees.emp_id as emp_id, employees.name as name, employees.dept_id as dept_id, 
		sum(orders.order_amount) as emp_revenue -- aggregate function
		from employees
		left join orders on employees.emp_id = orders.emp_id
		group by employees.emp_id, employees.name -- group by clause
),
WithDeptInfo as (
		select *, sum(emp_revenue) over(partition by dept_id) as dept_revenue  from EmpInfo) -- Window Function
        -- distinct keyword is also used here
select distinct EmpInfo.emp_id, EmpInfo.name, EmpInfo.dept_id, EmpInfo.emp_revenue * 100/nullif(WithDeptInfo.dept_revenue, 0) as Contribution
from EmpInfo 
inner join WithDeptInfo on EmpInfo.dept_id = WithDeptInfo.dept_id;





-- 5. MAnagers whose subordinates outperforms them
-- Business Insight: Identifies Employees who perform better than their managers in a team

-- using aggregate function, group by and without distinct
with Managerinfo as (
		select employees.emp_id as emp_id, employees.name as name, employees.dept_id as dept_id, 
        sum(orders.order_amount) as revenue, employees.manager_id as manager_id
		from employees 
		left join orders on employees.emp_id = orders.emp_id
		group by employees.emp_id, employees.name
)
select m.dept_id, m.name as manager, m.revenue as revenue, e.name as employee, e.revenue as revenue
from Managerinfo m
join Managerinfo e on m.emp_id = e.manager_id
where m.revenue <= e.revenue;


-- using distinct and window function
with managers as (
	select  distinct employees.emp_id, employees.name, employees.dept_id, 
		sum(orders.order_amount) over(partition by orders.emp_id
									  order by orders.emp_id asc) as revenue,
	    employees.manager_id
	from employees
left join orders on employees.emp_id = orders.emp_id
)
select m.name as manager, m.revenue as manager_revenue, a.emp_id, a.name, a.dept_id, a.revenue
from managers m
join managers a on m.emp_id = a.manager_id
where a.revenue > m.revenue;





-- 6. Employees improving month over month
-- Business Insight: Identifies employees Who are performing better in every month
with MonthlyRevenue as (
select e.emp_id, e.name, e.dept_id, date_format(o.order_date, '%Y-%m') as YearMonth, 
sum(o.order_amount) as current_month_revenue
from employees e 
inner join orders o on e.emp_id = o.emp_id
group by e.emp_id, date_format(o.order_date, '%Y-%m')
),
LagRevenue as (
select *, lag(current_month_revenue) over(partition by emp_id order by YearMonth) as prev_month_revenue
from Monthlyrevenue
)
select *, (current_month_revenue-prev_month_revenue)*100/nullif(current_month_revenue, 0) as Growth 
from LagRevenue where prev_month_revenue < current_month_revenue
and prev_month_revenue is not null;




-- 7. Department with negative growth 
-- Business Insight: Identifies the Team which shows negative growth compare to previous month
with MonthRevenue as (
	select  employees.dept_id as dept_id, date_format(orders.order_date, '%Y-%m') as order_date, sum(order_amount) as CurrentMonthRevenue
	from employees 
	inner join orders on employees.emp_id = orders.emp_id
	group by employees.dept_id, date_format(orders.order_date, '%Y-%m')
	order by employees.dept_id asc, date_format(orders.order_date, '%Y-%m') asc
),
MonthGrowth as (
	select dept_id, order_date, CurrentMonthRevenue, lag(CurrentMonthRevenue) over (partition by dept_id order by order_date)
		as PreviousMonthRevenue,
		CurrentMonthRevenue - lag(CurrentMonthRevenue) over (partition by dept_id order by order_date)
		as Growth from MonthRevenue
)
select * from MonthGrowth where Growth < 0;





-- 8. Top 20% employees per department by revenue (using window functions properly)
-- Business Insight: Identifies top performer in each department
with EmpRevenue as (		
        select employees.emp_id, employees.name, employees.dept_id, sum(orders.order_amount) as revenue
		from employees
		left join orders on employees.emp_id = orders.emp_id
		group by employees.emp_id, employees.name
),
PerformRank as (
		select *, ntile(5) over(partition by dept_id order by revenue desc) as ranking
        from EmpRevenue
)
select * from PerformRank
where ranking = 1 and revenue is not null;





-- 9. Departments with 3 consecutive negative growth months
-- Business Insight: identifies department with negative growth
WITH DeptMonthlyRev AS (
    select d.dept_id, d.dept_name, DATE_FORMAT(o.order_date, '%Y-%m-01') AS month_start,
        SUM(o.order_amount) AS revenue
    from departments d
    join employees e on d.dept_id = e.dept_id
    join orders o on e.emp_id = o.emp_id
    group by d.dept_id, d.dept_name, month_start
),

GrowthCalc as (
    select dept_id, dept_name, month_start, revenue,
        lag(revenue) over (partition by dept_id 
							order by month_start) as prev_revenue,
        revenue - lag(revenue) over (partition by dept_id 
									 order by month_start) as growth
    from DeptMonthlyRev
),

Streaks as (
    select
        *,
        CASE when growth < 0 then 1 else 0 end as is_negative,
        row_number() over (
            partition by dept_id 
            order by month_start
        ) 
        -
        row_number() over (
            partition by dept_id, 
            case when growth < 0 then 1 else 0 end
            order by month_start
        ) as grp
    from GrowthCalc
)

select dept_id from Streaks where is_negative = 1
group by dept_id, dept_name, grp
having COUNT(*) >= 3;





-- 10. Rolling 3-month average revenue per department
-- Business Insight: Average revenue generated by department in past 3 months

-- This is a strict 3-Month Average
with DeptMonthlyRevenue as (
		select d.dept_id, d.dept_name, date_format(o.order_date, '%Y-%m') as YearMonth,
		sum(o.order_amount) as Revenue
		from departments d
		join employees e on d.dept_id = e.dept_id
		join orders o on e.emp_id = o.emp_id
		group by
		d.dept_id, d.dept_name, date_format(o.order_date, '%Y-%m')
)
select dept_id, dept_name, YearMonth, Revenue,
case 
	when count(*) over (partition by dept_id order by YearMonth
						rows between 2 preceding and current row) = 3
	then avg(Revenue) over (partition by dept_id order by YearMonth
							rows between 2 preceding and current row)
	else null
end as rolling_3_month_avg 
from DeptMonthlyRevenue
order by dept_id, YearMonth;


-- this is not strict 
with DeptMonthlyRevenue as (
		select d.dept_id, d.dept_name, date_format(o.order_date, '%Y-%m') as YearMonth,
		sum(o.order_amount) as Revenue
		from departments d
		join employees e on d.dept_id = e.dept_id
		join orders o on e.emp_id = o.emp_id
		group by
		d.dept_id, d.dept_name, date_format(o.order_date, '%Y-%m')
)
select dept_id, dept_name, YearMonth, revenue, avg(revenue) over(partition by dept_id
											 order by YearMonth
                                             rows between 2 preceding and current row) as avg_3months
from DeptMonthlyRevenue
order by dept_id, YearMonth;